language: erlang
otp_release:
  - 23.0.1
  - 22.3.4
  - 21.3.8.1
  - 20.3.8.5
  - 19.3
before_script:
  - rebar3 get-deps
script: rebar3 compile || echo "cowlib1 is not actively maintained"
after_script:
  - rebar3 clean
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
